bellshade/OpenSeries

README.md

docs: merubah kata dan variable

---

OpenSeries/matematika.py
testing/main_test.py
testing/matematika_test.py

menambahkan konversi matematika
linked issue #NOMOR_ISSUE

feat: menambahkan konversi matematika

---

.github/pull_request_template.md
.mergify.yml
CONTRIBUTING.md

menambahkan bot auto merge dengan label
linked issue #9

chore: menambahkan konfigurasi mergify

---

.github/workflows/pypi.yml
pyproject.toml

test rilis dengan menggunakan branch dari main

fix: mencoba menggunakan ke branch release

---

.github/workflows/pypi.yml
.github/workflows/pythontesting.yml
.mergify.yml
CONTRIBUTING.md
pyproject.toml

merubah branch release menjadi `develop-library` dan hasil dari branch ini akan di push ke main untuk upload package ke pypi

chore: merubah branch release

---

OpenSeries/matematika.py
testing/main_test.py
testing/matematika_test.py

menambahkan fungsi dari euler pi
informasi lebih lanjut : [wikipedia](https://id.wikipedia.org/wiki/Fungsi_phi_Euler)

feat: menambahkan fungsi euler pi

---

OpenSeries/fisika.py
OpenSeries/matematika.py
OpenSeries/statistika.py
OpenSeries/util/constant.py
OpenSeries/util/error.py
README.md
example/fisika/kecepatan.py
example/matematika/radian_ke_derajat.py
testing/fisika_test.py
testing/matematika_test.py
testing/statistika_test.py

feat: upgrade dari error handling

---

app/docs/get-started/instalasi/page.mdx
app/docs/page.mdx
constants/documentations.ts

remove instalasi & informasi module link
- `os` = `macOS`
- `python` = `python3 -V (unix) / py -3 -V (Windows-Python launcher)`
linked issue #NOMOR_ISSUE

docs: remove instalasi & informasi module link

---

.dockerignore
Dockerfile.openseries_test
README.md
docker.sh
main.sh

Menambahkan dockerize untuk testing package OpenSeries
- `python` = `3.12`
linked issue #27

feat: dockerize for testing OpenSeries

---

pyproject.toml
setup.py

feat: deploy to pypi

---

OpenSeries/matematika.py
OpenSeries/util/constant.py

menggunakan variable dengan huruf kapital dimaksudkan untuk menandai variable yang bersifat konstanta, atau variable yang nilainya tidak dapat diubah

chore: merubah penamaan variabel konstan

---

OpenSeries/matematika.py
example/matematika/distribusi_binomial.py
setup_cp.py
testing/main_test.py
testing/matematika_test.py

distribusi binomial adalah distribusi probabilitas yang menggambarkan
probabilitas mendapatkan sejumlah keberhasilan tertentu dalam
serangkaian percobaan idependen, di mana setiap percobaan memilki dua
kemungkinan antara berhasil atau gagal

Distribusi binomial

---

OpenSeries/bilangan_istimewa.py
example/bilangan/armstrong.py
testing/bilangan_istimewa_test.py
testing/main_test.py

Angka Armstrong adalah bilangan bulat positif yang sama dengan jumlah pangkat tiga dari digit-digitnya
linked issue #37

feat: menambahkan angka armstrong

---

app/docs/fisika/kecepatan/page.mdx

docs: Mempebaharui dokumentasi

---

OpenSeries/bilangan_istimewa.py
example/bilangan/armstrong.py
example/bilangan/automorphic.py
testing/bilangan_istimewa_test.py
testing/main_test.py

angka automorphic adalah bilangan asli dalam basis bilangan tertentu yang kuadratnya "berakhir" dengan angka yang sama dengan bilangan itu sendiri
linked issue #37

chore: menambahkan angka automorphic

---

OpenSeries/matematika.py
OpenSeries/util/constant.py
dev-requirements.txt
example/matematika/nilai_faktorial.py
requirements.txt
testing/matematika_test.py

menambahkan library colorama untuk meningkatkan keterbacaan kode warna ANSI dan memperjelas nilai konstan

fix: improvisasi fungsi

---

OpenSeries/matematika.py
example/matematika/fungsi_gaussian.py
testing/main_test.py
testing/matematika_test.py

fungsi gaussian, yang biasa disebut fungsi kurva lonceng adalah fungsi
untuk mendeskripsikan probabilitas distribusi data yang normal

chore: menambahkan fungsi gaussian

---

OpenSeries/bilangan_istimewa.py
example/bilangan/pronic.py
testing/bilangan_istimewa_test.py
testing/main_test.py

angka pronic adalah bilangan bulat positif yang merupakan hasil perkalian dari dua bilangan bulat berurutan
linked issue #4 #37

chore: menambahkan angka pronic

---

OpenSeries/bilangan_istimewa.py
example/bilangan/segitiga.py
testing/bilangan_istimewa_test.py
testing/main_test.py

bilangan segitiga adalah bilangan yang dapat disusun dalam bentuk segitiga sama sisi
linked issue #4 #37

chore: menambahkan angka segitiga

---

README.md

chore: menambahkan badge

---

OpenSeries/__init__.py
OpenSeries/dasar.py
example/OpenSeries/bilangan_bulat.py
testing/dasar.py
testing/main_test.py

menambahkan matematika dasar sederhana, sebagai contoh
```python
import OpenSeries as opseries
print(opseries.bulat(2.3))
```
linked issue #60

chore: menambahkan fungsi membulatkan angka

---

OpenSeries/__init__.py
OpenSeries/dasar.py
testing/dasar.py
testing/main_test.py

menambahkan volume kubus
linked issue #60

chore: menambahkan fungsi volume kubus

---

OpenSeries/statistika.py
example/statistika/variance.py
testing/main_test.py
testing/statistika_test.py

variance merupakan konsep matematika untuk mengetahui keragamaman
nilai pada data terhadap penyebaran nilai rata-rata.
- `python` = `python3.11.6`
linked issue #NOMOR_ISSUE

Add algorithm

---

OpenSeries/util/error.py

menambhkan penjelasan tentang error log pada error konstan
- `python` = `3.12.4`

chore(minor): improvisasi minor error-log

---

OpenSeries/bilangan_istimewa.py
OpenSeries/matematika.py
OpenSeries/statistika.py
OpenSeries/util/constant.py
setup.py

menambahkan komentar kode
- `python` = `3.12.4`

chore(docs): menambahkan komentar kode

---

OpenSeries/bilangan_istimewa.py
testing/bilangan_istimewa_test.py
testing/main_test.py

menambahkan angka katalan
- `python` = `3.14.2`
linked issue #60

chore: menambahkan fungsi dari angka katalan

---

OpenSeries/util/constant.py
OpenSeries/util/error.py
OpenSeries/util/validasi.py
setup.py

Membuat fungsi helper untuk validasi nilai
- `python` = `3.12.5`
linked issue #60

chore: update fungsi untuk validasi nilai
